import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const products = [
  // ARIRANG Tour Core (Apparel)
  {
    name: '[ARIRANG] S/S T-Shirt (Black)',
    price: 58,
    images: ['IMG_2893.jpeg', 'IMG_2894.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 3,
    description: 'Official ARIRANG tour S/S t-shirt in black. Premium quality cotton blend.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 2 * 60 * 60 * 1000 + 14 * 60 * 1000),
  },
  {
    name: '[ARIRANG] Photo S/S T-Shirt (Vintage Black)',
    price: 62,
    images: ['IMG_2895.jpeg', 'IMG_2896.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 2,
    description: 'Vintage-style photo print S/S t-shirt from ARIRANG tour.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 47 * 60 * 1000),
  },
  {
    name: '[ARIRANG] Tour Cities S/S T-Shirt (Black)',
    price: 58,
    images: ['IMG_2897.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 8,
    description: 'Tour cities print S/S t-shirt featuring all ARIRANG tour dates.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 6 * 60 * 60 * 1000 + 15 * 60 * 1000),
  },
  {
    name: '[ARIRANG] Camo Crop T-Shirt (Ivory)',
    price: 52,
    images: ['IMG_2898.jpeg', 'IMG_2899.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 4,
    description: 'Camouflage crop t-shirt in ivory. Perfect for festival wear.',
    sizes: ['XS', 'S', 'M', 'L'],
    countdownEnd: new Date(Date.now() + 1 * 60 * 60 * 1000 + 58 * 60 * 1000),
  },
  {
    name: '[ARIRANG] Logo S/S T-Shirt (Black)',
    price: 58,
    images: ['IMG_2900.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 1,
    description: 'Minimalist ARIRANG logo on black t-shirt.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 23 * 60 * 1000),
  },
  {
    name: '[ARIRANG] Hoodie (Gray)',
    price: 125,
    images: ['IMG_2901.jpeg', 'IMG_2902.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 2,
    description: 'Cozy ARIRANG hoodie in heather gray. Perfect for tour fans.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 1 * 60 * 60 * 1000 + 3 * 60 * 1000),
  },
  {
    name: '[ARIRANG] Sweatpants (Gray)',
    price: 95,
    images: ['IMG_2903.jpeg', 'IMG_2904.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 6,
    description: 'Comfortable gray sweatpants with embroidered ARIRANG logo.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 4 * 60 * 60 * 1000 + 47 * 60 * 1000),
  },
  {
    name: '[ARIRANG] Windbreaker (Gray)',
    price: 145,
    images: ['IMG_2905.jpeg', 'IMG_2906.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Pre-order · Ships Sep 2026',
    stock: 3,
    description: 'Lightweight windbreaker perfect for outdoor events.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 2 * 60 * 60 * 1000 + 55 * 60 * 1000),
  },
  {
    name: '[ARIRANG] Knit Cardigan (Cream/Navy)',
    price: 185,
    images: ['IMG_2907.jpeg', 'IMG_2908.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 1,
    description: 'Premium knit cardigan in cream with navy accents.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 12 * 60 * 1000),
  },

  // RUN SEOKJIN EP.TOUR (Apparel)
  {
    name: '[RUN SEOKJIN] EP.TOUR S/S T-Shirt (Blue)',
    price: 55,
    images: ['IMG_2909.jpeg', 'IMG_2910.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Pre-order · Ships Jul 2026',
    stock: 9,
    description: 'Blue S/S t-shirt from RUN SEOKJIN EP.TOUR collection.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 7 * 60 * 60 * 1000 + 45 * 60 * 1000),
  },
  {
    name: '[RUN SEOKJIN] EP.TOUR Long Sleeve (Heather)',
    price: 65,
    images: ['IMG_2911.jpeg', 'IMG_2912.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Pre-order · Ships Jul 2026',
    stock: 5,
    description: 'Heather long sleeve shirt from RUN SEOKJIN collection.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 3 * 60 * 60 * 1000 + 51 * 60 * 1000),
  },
  {
    name: '[RUN SEOKJIN] EP.TOUR Coach Jacket (Black)',
    price: 135,
    images: ['IMG_2913.jpeg', 'IMG_2914.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Pre-order · Ships Jul 2026',
    stock: 2,
    description: 'Vintage-inspired coach jacket in black.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 1 * 60 * 60 * 1000 + 28 * 60 * 1000),
  },
  {
    name: '[RUN SEOKJIN] EP.TOUR Denim Jacket',
    price: 155,
    images: ['IMG_2915.jpeg', 'IMG_2916.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Pre-order · Ships Jul 2026',
    stock: 3,
    description: 'Premium denim jacket with embroidered logo.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 2 * 60 * 60 * 1000 + 51 * 60 * 1000),
  },

  // Member Solo Jerseys (Apparel)
  {
    name: '[JIN] Baseball Jersey (Camo Black)',
    price: 85,
    images: ['IMG_2917.jpeg', 'IMG_2918.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 4,
    description: 'Jin solo baseball jersey with camouflage design.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 3 * 60 * 60 * 1000 + 17 * 60 * 1000),
  },
  {
    name: '[RM] Baseball Jersey (Camo Black)',
    price: 85,
    images: ['IMG_2919.jpeg', 'IMG_2920.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 5,
    description: 'RM solo baseball jersey with camouflage design.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 4 * 60 * 60 * 1000 + 22 * 60 * 1000),
  },
  {
    name: '[SUGA] Baseball Jersey (Camo Black)',
    price: 85,
    images: ['IMG_2921.jpeg', 'IMG_2922.jpeg', 'IMG_2923.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 5,
    description: 'SUGA solo baseball jersey with camouflage design and label detail.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 4 * 60 * 60 * 1000 + 55 * 60 * 1000),
  },

  // j-hope HOPE ON THE STAGE (Apparel)
  {
    name: '[j-hope] HOPE ON THE STAGE S/S T-Shirt (Red)',
    price: 55,
    images: ['IMG_2924.jpeg', 'IMG_2925.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 7,
    description: 'Red S/S t-shirt from j-hope HOPE ON THE STAGE collection.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 6 * 60 * 60 * 1000 + 33 * 60 * 1000),
  },
  {
    name: '[j-hope] HOPE ON THE STAGE Hoodie (Black)',
    price: 125,
    images: ['IMG_2926.jpeg', 'IMG_2927.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 2,
    description: 'Black hoodie from j-hope HOPE ON THE STAGE collection.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 1 * 60 * 60 * 1000 + 7 * 60 * 1000),
  },
  {
    name: '[j-hope] HOPE ON THE STAGE Striped Polo',
    price: 68,
    images: ['IMG_2928.jpeg', 'IMG_2929.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 3,
    description: 'Striped polo shirt from j-hope collection.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 2 * 60 * 60 * 1000 + 44 * 60 * 1000),
  },
  {
    name: '[j-hope] HOPE ON THE STAGE Knit Cardigan',
    price: 195,
    images: ['IMG_2930.jpeg'],
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 1,
    description: 'Premium knit cardigan from j-hope HOPE ON THE STAGE collection.',
    sizes: ['S', 'M', 'L', 'XL'],
    countdownEnd: new Date(Date.now() + 18 * 60 * 1000),
  },

  // Accessories
  {
    name: '[RUN SEOKJIN] EP.TOUR Backpack (Blue)',
    price: 85,
    images: ['IMG_2931.jpeg', 'IMG_2932.jpeg', 'IMG_2933.jpeg'],
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Pre-order · Ships Jul 2026',
    stock: 5,
    description: 'Blue backpack with multiple compartments from RUN SEOKJIN collection.',
    sizes: ['One Size'],
    countdownEnd: new Date(Date.now() + 4 * 60 * 60 * 1000 + 9 * 60 * 1000),
  },
  {
    name: '[ARIRANG] Official Light Stick Ver.4',
    price: 69,
    images: ['IMG_2934.jpeg'],
    category: 'Light Stick',
    badges: ['EXCLUSIVE', 'PRE-ORDER'],
    shippingTag: 'Shipped from US',
    stock: 3,
    description: 'Official ARIRANG light stick version 4 with color changing modes.',
    sizes: ['One Size'],
    countdownEnd: new Date(Date.now() + 2 * 60 * 60 * 1000 + 30 * 60 * 1000),
  },
  {
    name: '[ARIRANG] Official Light Stick Bag',
    price: 53,
    images: ['IMG_2935.jpeg'],
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'PRE-ORDER'],
    shippingTag: 'Shipped from US',
    stock: 4,
    description: 'Official light stick carrying bag with embroidered logo.',
    sizes: ['One Size'],
    countdownEnd: new Date(Date.now() + 3 * 60 * 60 * 1000 + 15 * 60 * 1000),
  },
  {
    name: '[ARIRANG] Laptop Pouch',
    price: 60,
    images: ['IMG_2936.jpeg'],
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 6,
    description: 'Durable laptop pouch with ARIRANG branding. Fits up to 13" laptops.',
    sizes: ['One Size'],
    countdownEnd: new Date(Date.now() + 5 * 60 * 60 * 1000 + 45 * 60 * 1000),
  },
  {
    name: '[ARIRANG] Candle',
    price: 59,
    images: ['IMG_2937.jpeg'],
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    shippingTag: 'Shipped from US',
    stock: 7,
    description: 'Scented candle with ARIRANG tour theme. Hand-poured soy wax.',
    sizes: ['One Size'],
    countdownEnd: new Date(Date.now() + 6 * 60 * 60 * 1000 + 20 * 60 * 1000),
  },
];

async function seed() {
  try {
    console.log('Seeding database...');

    for (const product of products) {
      await prisma.product.create({
        data: {
          ...product,
          images: JSON.stringify(product.images),
          badges: JSON.stringify(product.badges),
          sizes: JSON.stringify(product.sizes),
        },
      });
    }

    console.log(`✓ Seeded ${products.length} products`);
  } catch (error) {
    console.error('Seeding failed:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

seed();
