export interface Product {
  id: string;
  name: string;
  price: number;
  category: string;
  badges: string[];
  images: string[];
}

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Official Light Stick',
    price: 35.99,
    category: 'Light Stick',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-1-front.jpeg', 'product-1-back.jpeg', 'product-1-detail.jpeg', 'product-1-label.jpeg'],
  },
  {
    id: '2',
    name: 'Hoodie - Black',
    price: 59.99,
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-2-front.jpeg', 'product-2-back.jpeg', 'product-2-detail.jpeg'],
  },
  {
    id: '3',
    name: 'Graphic T-Shirt',
    price: 29.99,
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-3-front.jpeg', 'product-3-back.jpeg', 'product-3-detail.jpeg'],
  },
  {
    id: '4',
    name: 'Baseball Cap',
    price: 24.99,
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-4-front.jpeg', 'product-4-back.jpeg', 'product-4-label.jpeg'],
  },
  {
    id: '5',
    name: 'Crossbody Bag',
    price: 44.99,
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-5-front.jpeg', 'product-5-back.jpeg', 'product-5-detail.jpeg', 'product-5-label.jpeg'],
  },
  {
    id: '6',
    name: 'Beanie Hat',
    price: 19.99,
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-6-front.jpeg', 'product-6-back.jpeg'],
  },
  {
    id: '7',
    name: 'Crew Socks Pack',
    price: 15.99,
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-7-front.jpeg', 'product-7-detail.jpeg'],
  },
  {
    id: '8',
    name: 'Phone Case',
    price: 19.99,
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-8-front.jpeg', 'product-8-back.jpeg', 'product-8-detail.jpeg'],
  },
  {
    id: '9',
    name: 'Tote Bag',
    price: 22.99,
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-9-front.jpeg', 'product-9-back.jpeg', 'product-9-detail.jpeg'],
  },
  {
    id: '10',
    name: 'Slap Bracelet',
    price: 9.99,
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-10-front.jpeg'],
  },
  {
    id: '11',
    name: 'Zip Hoodie',
    price: 64.99,
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-11-front.jpeg', 'product-11-back.jpeg', 'product-11-detail.jpeg'],
  },
  {
    id: '12',
    name: 'Long Sleeve Tee',
    price: 34.99,
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-12-front.jpeg', 'product-12-back.jpeg', 'product-12-detail.jpeg'],
  },
  {
    id: '13',
    name: 'Sweatpants',
    price: 54.99,
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-13-front.jpeg', 'product-13-back.jpeg', 'product-13-detail.jpeg'],
  },
  {
    id: '14',
    name: 'Baseball Jersey',
    price: 49.99,
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-14-front.jpeg', 'product-14-back.jpeg', 'product-14-label.jpeg'],
  },
  {
    id: '15',
    name: 'Oversized Tee',
    price: 32.99,
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-15-front.jpeg', 'product-15-back.jpeg', 'product-15-detail.jpeg'],
  },
  {
    id: '16',
    name: 'Bucket Hat',
    price: 27.99,
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-16-front.jpeg', 'product-16-back.jpeg', 'product-16-label.jpeg'],
  },
  {
    id: '17',
    name: 'Keychain',
    price: 7.99,
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-17-front.jpeg', 'product-17-detail.jpeg'],
  },
  {
    id: '18',
    name: 'Water Bottle',
    price: 18.99,
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-18-front.jpeg', 'product-18-side.jpeg'],
  },
  {
    id: '19',
    name: 'Scarf',
    price: 34.99,
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-19-front.jpeg', 'product-19-folded.jpeg'],
  },
  {
    id: '20',
    name: 'Hair Clip Set',
    price: 12.99,
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-20-front.jpeg', 'product-20-detail.jpeg'],
  },
  {
    id: '21',
    name: 'Track Pants',
    price: 52.99,
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-21-front.jpeg', 'product-21-back.jpeg', 'product-21-detail.jpeg'],
  },
  {
    id: '22',
    name: 'Graphic Hoodie',
    price: 62.99,
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-22-front.jpeg', 'product-22-back.jpeg', 'product-22-detail.jpeg', 'product-22-label.jpeg'],
  },
  {
    id: '23',
    name: 'Crop Top',
    price: 26.99,
    category: 'Apparel',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-23-front.jpeg', 'product-23-back.jpeg', 'product-23-detail.jpeg'],
  },
  {
    id: '24',
    name: 'Backpack',
    price: 74.99,
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-24-front.jpeg', 'product-24-back.jpeg', 'product-24-detail.jpeg', 'product-24-side.jpeg'],
  },
  {
    id: '25',
    name: 'Beaded Necklace',
    price: 16.99,
    category: 'Accessories',
    badges: ['EXCLUSIVE', 'LIMITED'],
    images: ['product-25-front.jpeg', 'product-25-detail.jpeg'],
  },
];
